pool:
  vmImage: windows-2019

variables:
  solution: './ClientLibrary/Samples/ClientSamples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: PublishSymbols@1
  inputs:
    ConnectedServiceName: 'MCAPS-Support-REQ-99605-2024-shmohanty(fd9365e2-b355-4a33-9b57-b8fd8c244341)'
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'


